sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "node"
  - "10"
  - "8"
install: npm install
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
