sudo: false
notifications:
  email: false

language: node_js
node_js:
  - "node"
  - "12"
  - "10"

install:
  - if [[ $TRAVIS_BRANCH =~ greenkeeper ]]; then
      npm install;
    else
      npm ci;
    fi
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
