sudo: false
notifications:
  email: false

language: node_js
node_js:
  - "16"
  - "14"

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - latest

install:
  - npm ci;
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
